# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16a065f9b233eb5ac92518d2e9c6d4402ae28e50921e04fa3f8182077ed789d5df0b18eda1d1766b425ec9d0dec270c40f9b1ebbc1506f7a81ef40fd1bab715b

test:
  secret_key_base: ddd2e8c7c5ef97dc9df37f65b23f1c3b331741f2743a967845e66b0d749044b4d4c7840338365b04c3d1b24930603cbd6cf6c80b0e609cb3a56359035f0439bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
